[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn vibe.wsgi --workers 1 --timeout 120"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
