# Generated by Django 5.2.13 on 2026-04-14 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=500)),
                ('authors', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('avg_rating', models.FloatField(default=0)),
                ('ratings_count', models.IntegerField(default=0)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('genres', models.CharField(blank=True, max_length=500)),
                ('embedding', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'books',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('user', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to='books.user')),
            ],
            options={
                'db_table': 'library',
                'unique_together': {('user', 'title')},
            },
        ),
    ]
